// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhM4kTdohD533IvamI0avCIv78MlFgRss',
    appId: '1:179056535088:web:6c1835e18dd279a4c7eff5',
    messagingSenderId: '179056535088',
    projectId: 'flutterchat-88724',
    authDomain: 'flutterchat-88724.firebaseapp.com',
    storageBucket: 'flutterchat-88724.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHXJwdRyu-zcN9axkN70LYbHURVgDz5SU',
    appId: '1:179056535088:android:82b777bf0d1e8a86c7eff5',
    messagingSenderId: '179056535088',
    projectId: 'flutterchat-88724',
    storageBucket: 'flutterchat-88724.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAegiyktQGYTdOaq5k-Le_O1ugYNK9zDZM',
    appId: '1:179056535088:ios:d463b210683954f8c7eff5',
    messagingSenderId: '179056535088',
    projectId: 'flutterchat-88724',
    storageBucket: 'flutterchat-88724.appspot.com',
    iosClientId: '179056535088-3qmd1srd2ba3qn6h0j5eakl7bodk1odq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAegiyktQGYTdOaq5k-Le_O1ugYNK9zDZM',
    appId: '1:179056535088:ios:bde0e2e5694141ccc7eff5',
    messagingSenderId: '179056535088',
    projectId: 'flutterchat-88724',
    storageBucket: 'flutterchat-88724.appspot.com',
    iosClientId: '179056535088-7rqa53ok5p4jm6na1bsif72opqei18ra.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat.RunnerTests',
  );
}
